[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#F97316"

[runner]
magicEnabled = true
fastReruns = true

[client]
showErrorDetails = true
